### ISSUE TITLE
PickerController doesn't show correctly

### ISSUE THREAD

**Issue by mariossavva** [ionic-team/ionic-framework#17664]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The second time the PickerController shows the options are not showing correctly. 

**Expected behavior:**

It should show always the right options
![pickercontroller](https://user-images.githubusercontent.com/32732988/53690523-35b59180-3d3a-11e9-9257-ebf9b43d90f2.png)

**Steps to reproduce:**

**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.13.4
   @angular-devkit/schematics    : 7.3.4
   @angular/cli                  : 7.3.4
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.15.1 (/usr/local/bin/node)
   npm    : 6.8.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you share a repository with the code required to reproduce this issue? Thanks!

**Comment by mariossavva** [comment]
Here's a simple example (home.page.ts) from a new blank project. Hope this helps...

```
import { Component } from '@angular/core';
import { PickerController } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  values = [
    { value: 1, text: 'value 1' },
    { value: 2, text: 'value 2' },
    { value: 3, text: 'value 3' },
    { value: 4, text: 'value 4' },
    { value: 5, text: 'value 5' }
  ]

  _selectedIndex: number = 0;

  constructor(private pickerCtrl: PickerController) { }

  async showPicker() {
    const picker = await this.pickerCtrl.create({
      buttons: [
        { text: 'Cancel' },
        {
          text: 'Done',
          handler: (value) => {
            const v = value.pick.value;
            this._selectedIndex = this.values.findIndex(i => i.value == v);
            console.log(this._selectedIndex);
          }
        }
      ],
      columns: [
        {
          name: 'pick',
          // if selectedIndex is set through a variable the view is messed up
          // selectedIndex: 2, // this works
          selectedIndex: this._selectedIndex, // this messes up the view
          options: this.values
        }
      ]
    });
    picker.present();
  }
}
```

**Comment by liamdebeasi** [comment]
Thanks for the code! This is what I see when I try it out in a blank Ionic start (`ionic start myApp blank`): 
![image](https://user-images.githubusercontent.com/2721089/53810996-4dea0400-3f26-11e9-99e2-7f90bf5f8d6c.png)

Which browser/version are you testing this one?

**Comment by mariossavva** [comment]
@liamdebeasi hi. i am using Chrome 72.

Here are the step that I got the issue:
The first time you select the controller it shows correctly.
Then pick an option say "value 3" and click Ok.
Then the second time you show the picker the options don't show correctly if the selectedIndex is set.

I hope this helps

**Comment by liamdebeasi** [comment]
Thanks for the follow up! I can reproduce this issue. We will look into it!

**Comment by Stromberg** [comment]
I have the same issue.

**Comment by zwlccc** [comment]
You can test it using the following methods:
Modify the picker-column.tsx file：
1.` private update(y: number, duration: number, saveY: boolean) {
    if (!this.optsEl) {
      return;
    }

    // ensure we've got a good round number :)
    let translateY = 0;
    let translateZ = 0;
    const { col, rotateFactor } = this;
    const selectedIndex = col.selectedIndex = this.indexForY(-y);
    const durationStr = (duration === 0) ? '' : duration + 'ms';
    const scaleStr = `scale(${this.scaleFactor})`;

    const children = this.optsEl.children;
    for (let i = 0; i < children.length; i++) {
      const button = children[i] as HTMLElement;
      const opt = col.options[i];
      const optOffset = (i * this.optHeight) + y;
      let transform = '';

      if (rotateFactor !== 0) {
        const rotateX = optOffset * rotateFactor;
        if (Math.abs(rotateX) <= 90) {
          translateY = 0;
          translateZ = 90;
          transform = `rotateX(${rotateX}deg) `;
        } else {
          translateY = -9999;
        }

      } else {
        translateZ = 0;
        translateY = optOffset;
      }

      const selected = selectedIndex === i;
      transform += `translate3d(0px,${translateY}px,${translateZ}px) `;
      if (this.scaleFactor !== 1 && !selected) {
        transform += scaleStr;
      }

      // Update transition duration
      if (this.noAnimate) {
        opt.duration = 0;
        button.style.transitionDuration = '';

      } else if (duration !== opt.duration) {
        opt.duration = duration;
        button.style.transitionDuration = durationStr;
      }

      // Update transform
      if (transform !== opt.transform) {
        opt.transform = transform;
        button.style.transform = transform;
      }
      // Update selected item
      if (selected !== opt.selected) {
        opt.selected = selected;
        if (selected) {
          button.classList.add(PICKER_OPT_SELECTED);
        } else {
          button.classList.remove(PICKER_OPT_SELECTED);
        }
      }
    }
    this.col.prevSelected = selectedIndex;

    if (saveY) {
      this.y = y;
    }

    if (this.lastIndex !== selectedIndex) {
      // have not set a last index yet
      hapticSelectionChanged();
      this.lastIndex = selectedIndex;
    }
  }
`;
2.`render() {
    const col = this.col;
    const Button = 'button' as any;
    return [
      col.prefix && (
        <div class="picker-prefix" style={{ width: col.prefixWidth! }}>
          {col.prefix}
        </div>
      ),
      <div
        class="picker-opts"
        style={{ maxWidth: col.optionsWidth! }}
        ref={el => this.optsEl = el}
      >
        { col.options.map((o, index) =>
          <Button
            type="button"
            class={{ 'picker-opt': true, 'picker-opt-disabled': !!o.disabled }}
            **style={{ transform: o.transform ? o.transform : 'translate3d(0px, -9999px, 90px)', 'transition-duration': o.duration ? o.duration: TRANSITION_DURATION + 'ms' }}**
            opt-index={index}
          >
            {o.text}
          </Button>
        )}
      </div>,
      col.suffix && (
        <div class="picker-suffix" style={{ width: col.suffixWidth! }}>
          {col.suffix}
        </div>
      )
    ];
  }`.

**Comment by nvahalik** [comment]
@liamdebeasi: I think @zwlccc is on the right track, here.

Other observations: When trying to recreate the issue using the base ionic code base, I could not get it to occur. Perhaps it's something that is only present in the Angular bindings?

**Comment by pppp0836** [comment]
I have same issue too,Expect good news

**Comment by zwlccc** [comment]
@nvahalik No, this is a problem with rendering styles. Dynamically set options. A rendering style error occurs,When the number of new options is greater than the old number of options.

**Comment by MengLu2016** [comment]
it is the problem of changed columns.options with dynamically set options, when click the picker without changing the selectedIndex twice, the columns.options will add three attribute of selected/duration/transform, just delete it.
columns.options.forEach(element => {
            delete element.selected;
            delete element.duration;
            delete element.transform;
        });

**Comment by nvahalik** [comment]
Indeed! That does indeed fix it for me

**Comment by zwlccc** [comment]
@MengLu2016 This doesn't work for my components.[ionic4-city-picker](https://github.com/zwlccc/ionic4-city-picker)

**Comment by nparasur** [comment]
I was able to reproduce it, but was able to workaround it. The issue seems to be the way the values are set for the PickerColumnOptions. I did not have any issue with SelectedIndex being set dynamically. Note that the Ionic DatePicker component (see src when you have a chance) used PickerController .
In my case I ended up with below.......................

You could do either
1.  Explicitly set the Options - array as such
............
columns: [
        {
          name: 'hours',
          selectedIndex: this.hrlyReminder.repeat-1, // this is where we set the default selection
          options: [
             { text: 'Every 1 hour', value: '1' },
             { text: 'Every 2 hours', value: '2' },
             { text: 'Every 3 hours', value: '3' },
             { text: 'Every 4 hours', value: '4' },
           ]      
         }
...........

OR
2.  thru a function as such....

.......
createPickerColumnOptions() :  PickerColumnOption[] {
    let hoursData:PickerColumnOption[] = [
      { text: 'Every 1 hour', value: '1' },
      { text: 'Every 2 hours', value: '2' },
      { text: 'Every 3 hours', value: '3' },
      { text: 'Every 4 hours', value: '4' }
    ];
    console.log('Data is ' + JSON.stringify(hoursData));
    return hoursData;
  }
..........
..........
columns: [
        {
          name: 'hours',
          selectedIndex: this.hrlyReminder.repeat-1, // this is where we set the default selection
          options: this.createPickerColumnOptions()       
          
        }
      ]

**Comment by a7md0** [comment]
I have the same issue using chrome browser. The solution by @MengLu2016 is working perfectly.

```
Ionic:
   Ionic CLI                     : 5.2.3 (AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:
   Android SDK Tools : 26.1.1 (Android\Sdk)
   NodeJS            : v10.0.0 (nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by michaelins** [comment]
@MengLu2016 Could you show a full demo of your workaround? I just tried and it doesn't work for me. Thanks.

**Comment by a7md0** [comment]
@michaelins 
```
async numberPicker() {
    const picker = await this.pickerCtrl.create({
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel'
        },
        {
          text: 'Confirm',
          handler: (data) => {
            console.log(data.number);
          }
        }
      ],
      columns: [{
        name: 'number',
        options: [
          { text: 'One', value: 1 },
          { text: 'Two', value: 2 },
        ]
      }]
    });

    picker.columns[0].options.forEach(element => {
      delete element.selected;
      delete element.duration;
      delete element.transform;
    });

    picker.present();
  }
```

**Comment by michaelins** [comment]
@liamdebeasi is there a fix coming soon? I really need this...

**Comment by michaelins** [comment]
@a7md0 thank you but didn't work for me. When I update the columns i.e. replace column options with new ones, all new options are stacked again.

**Comment by zwlccc** [comment]
@jwhiteaei Thank you for your help. I will try to see if this method works in my component.

**Comment by belkka** [comment]
It looks like the same `PickerOptions` object must not be reused for several pickers. I. e. if you store it in component instance, do a copy before passing to `pickerController.create()`:
```
const opts = JSON.parse(JSON.stringify(this.opts));
const picker = await this.pickerController.create(opts);
```

**Comment by halkhateeb** [comment]
Hi there,
I think we are dealing with two separate problems here:

1- If you get all your options stacked once you reopen the picker, then the solution suggested by @MengLu2016 should solve your problem

2- If you are working with dynamic options, in my case I have 2 columns where the options in column B depends on the value selected by column A. You need to make sure that options in column B always have the same length. Otherwise, you might see stacked options if the number of the new options is greater than the number of the old options as @zwlccc said. So what I did, is to make sure that all possible options have the same length by adding disabled options by the end of the smaller one.

For example:
```
PossibleOptionsForColumnB = [
    [
      { value: 1, text: 'value 1' },
      { value: 2, text: 'value 2' },
      { value: 3, text: 'value 3' },
      { value: 4, text: 'value 4' },
      { value: -1, text: '', disabled: true }
    ],
    [
      { value: 1, text: 'value 1' },
      { value: 2, text: 'value 2' },
      { value: 3, text: 'value 3' },
      { value: 4, text: 'value 4' },
      { value: 5, text: 'value 5' }
    ]
    ,
    [
      { value: 1, text: 'value 1' },
      { value: 2, text: 'value 2' },
      { value: 3, text: 'value 3' },
      { value: -1, text: '', disabled: true },
      { value: -1, text: '', disabled: true }
    ]
  ];
```

**Comment by michaelins** [comment]
@halkhateeb your solution works like a charm! Thank you for saving my day.

**Comment by nurizzatiabdharis** [comment]
@Galiza i've got the same problem as you but your solution doesn't work for me. Any ideas why?

**Comment by Galiza** [comment]
@nurizzatiabdharis Very strange, here's how I solved it:
```
async openPicker() {
    this.removeAllAddedAttributesToArray();
    const pickerElement = await this.pickerCtrl.create({
      buttons: [
        {
          text: CANCEL,
          cssClass: 'cancel-btn',
          role: 'cancel'
        },
        {
          text: DONE,
          cssClass: 'done-btn',
          role: 'done',
          handler: (data) => {
            this.changeValue(data.value);
          }
        }
      ],
      columns: [{
        name: 'col',
        options: this.simpleColumns,
        selectedIndex: this.selectedIndex
      }],
      cssClass: 'ion-picker',
    });

    await pickerElement.present();
}

private removeAllAddedAttributesToArray() {
    this.simpleColumns.forEach((data) => {
      if (data.duration) {
        delete data.transform;
        delete data.duration;
        delete data.selected;
      }
    });
  }
```

**Comment by punixxher** [comment]
This work for me @nurizzatiabdharis thanks.

**Comment by netsesame2** [comment]
I got the same issue when use dynamic column options. Just as @zwlccc @halkhateeb, if the new options has short length than current one, overlay will happen.
Can be produced in both ionic 4.x and 5.x.

@halkhateeb gives a workaround to add some disabled options, although the disabled options can still be scrolled, but till now it seems the only solution.

@zwlccc gives some patch to the source in his repo, hope ionic team can think of it.

**Comment by ishaiavrahami** [comment]
Experiencing the same issue.. 
![image](https://user-images.githubusercontent.com/33962719/80678854-bd577700-8a89-11ea-9f2f-922d5130a836.png)

**Comment by janbuerling** [comment]
Any solution for dynamic column options?

I tried disabling the options, but then I had a strange behavior. The options are no longer displayed, but still selectable.

<img width="413" alt="Bildschirmfoto 2020-05-03 um 12 44 43" src="https://user-images.githubusercontent.com/18394509/80912270-15b59f80-8d3c-11ea-93db-2f0eba86d2c2.png">

**Comment by earth774** [comment]
I do not work any more T^T
![Uploading localhost_8100_activity(Galaxy S5).png…]()

**Comment by earth774** [comment]
I do not work any more T^T
![localhost_8100_activity(Galaxy S5)](https://user-images.githubusercontent.com/13549987/81322371-15136500-90be-11ea-9c81-8b0a4cd2f579.png)

**Comment by gusterwoei** [comment]
Having the same issues on Ionic 5 React. First time opening the picker, the options are showing fine. Close it and open again the options will overlap.

**Comment by JavOLeeN** [comment]
Same problem on Ionic 5 Angular.

**Comment by olaisen81** [comment]
Same issue on Ionic 5 Angular

**Comment by patelrikin** [comment]
For those having issue with using IonPicker component in React. Here's my solution basically it just re-creates sortOptions on every render (not optimal but it is what it is until the "real" fix):

Place sortOptions inside the render() or if using functional component then place it inside the function declaration like below:

```
  const sortOptions: PickerColumn[] = [
    {
      name: "sortOption",
      options: [
        { text: "Apple", value: "red" },
        { text: "Banana", value: "yellow" },
        { text: "Orange", value: "orange" },
      ],
    },
  ];

```
And in your IonPicker it stays the same
```
<IonPicker
     //...
     columns={sortOptions}
     //...
    />
```


@gusterwoei FYI

**Comment by HeikoKanzler** [comment]
I had the same problem. Turned around the picker has issues if you also reuse column options, in my case I used a array of 60 values (for minutes and seconds) two times and the picker didn't display the seconds correctly on first time opening, while also showing the stacked items on all secondary opens.

So I 
1. used different arrays ( a copy)
2. used @jwhiteaei code (loop that removes selected, duration and transform)

Thank you all!

![Screenshot 2020-07-29 at 13 24 54](https://user-images.githubusercontent.com/5279575/88798111-ac132900-d1a4-11ea-8f63-0ea06b986b22.png)

**Comment by olaisen81** [comment]
> Hi there,
> I think we are dealing with two separate problems here:
> 
> 1- If you get all your options stacked once you reopen the picker, then the solution suggested by @MengLu2016 should solve your problem
> 
> 2- **If you are working with dynamic options, in my case I have 2 columns where the options in column B depends on the value selected by column A**. You need to make sure that options in column B always have the same length. Otherwise, you might see stacked options if the number of the new options is greater than the number of the old options as @zwlccc said. So what I did, is to make sure that all possible options have the same length by adding disabled options by the end of the smaller one.
> 
> For example:
> 
> ```
> PossibleOptionsForColumnB = [
>     [
>       { value: 1, text: 'value 1' },
>       { value: 2, text: 'value 2' },
>       { value: 3, text: 'value 3' },
>       { value: 4, text: 'value 4' },
>       { value: -1, text: '', disabled: true }
>     ],
>     [
>       { value: 1, text: 'value 1' },
>       { value: 2, text: 'value 2' },
>       { value: 3, text: 'value 3' },
>       { value: 4, text: 'value 4' },
>       { value: 5, text: 'value 5' }
>     ]
>     ,
>     [
>       { value: 1, text: 'value 1' },
>       { value: 2, text: 'value 2' },
>       { value: 3, text: 'value 3' },
>       { value: -1, text: '', disabled: true },
>       { value: -1, text: '', disabled: true }
>     ]
>   ];
> ```
@halkhateeb How to avoid column dependancy?

**Comment by andreslon** [comment]
Upgrading some packages it's was solved.
```
    "@ionic/react": "^5.3.4",
    "@ionic/react-router": "^5.3.4",
```
To upgrade just run:

`npm update`

**Comment by kheber92** [comment]
The problem with the stacked data still appears in Ionic Angular v5.x.
Even if I use the suggested fixes above, the data appears stacked for around 1 second before arranging correctly.

**Comment by sergiocarneiro** [comment]
2 years and the issue still exists.

Meanwhile I'll use @Galiza's workaround, it works.

**Comment by alzee** [comment]
> It looks like the same `PickerOptions` object must not be reused for several pickers. I. e. if you store options in component instance, do a copy before passing to `pickerController.create()`:
> 
> ```
> const opts = JSON.parse(JSON.stringify(this.opts));
> const picker = await this.pickerController.create(opts);
> ```

This is my situation.
Instead of clone opts, I moved columns setup code from `ngOnInit()` to `async openPicker()` right above `const picker = await this.pickerController.create()`, and problem solved.

**Comment by carlgik4** [comment]
I got a solution, but I can't reply it on ionicframework.org, then I found similar question here.

Anyway, this is my solution:
If you want to update options, you could make the options same count, such as first time you have 5 items, second time 10 items, you can pad them all to above 10 items, such as 100 items, all the padding items, you can mark them as disable, these disabled items will not be displayed, but the animation seems correct.

1st time:
options: [{text, value, disabled: false}..., {text, value, disabled: true}...] // 100items

2nd time:
options: [{text, value, disabled: false}..., {text, value, disabled: true}...] // 100items

It also works with picker.addEventListener('ionPickerColChange', async (event: any) => {}

`
document.addEventListener("ionPickerColChange", this.ionPickerColChange);

ionPickerColChange = (event: Event) => {
        console.log(event);
        const e: any = event;
        if (e.detail?.name === "first") {
            //each column should has enough disabled padding items
            this.columns = this.generateColumns(e.detail);
            if (this.picker?.current) {
                this.picker.current.columns = this.columns;
            }
        }
    };

render(){
...

<IonPicker
                        ref={this.picker}
                        isOpen={this.state.pickerOpen}
                        showBackdrop={true}
                        backdropDismiss={true}
                        onDidDismiss={() => {
                            this.setState({
                                pickerOpen: false
                            });
                        }}
                        columns={this.columns}
                        buttons={[
                            {
                                text: "Cancel",
                                role: "cancel",
                                handler: selected => {
                                    console.log(selected);
                                }
                            },
                            {
                                text: "Confirm",
                                handler: selected => {
                                    console.log(selected);
                                }
                            }
                        ]}
                    />
...
}
`

**Comment by reza3vi** [comment]
// just before => await picker.present();

// use:
	for (let col of picker.columns) {
		for (let opt of col.options) {
			delete opt.selected;
			delete opt.duration;
			delete opt.transform;
		}
	}

**Comment by yetkinaykan** [comment]
This problem persists in ionic 5 react version. (useIonPicker)

**Comment by guzmanoj** [comment]
As a workaround, I'm cleaning the original array of columns before showing the picker.
Here's a full example

```

import { Component, EventEmitter, Input, Output, TemplateRef, ViewChild } from '@angular/core';
import { PickerController } from '@ionic/angular';
import { PickerColumnOption } from '@ionic/core/dist/types/components/picker/picker-interface';

@Component({
  selector: 'app-picker',
  templateUrl: './picker.component.html',
  styleUrls: ['./picker.component.scss'],
})
export class PickerComponent {
  @Input() defaultLanguage!: PickerColumnOption;
  @Input() languagesList: Array<PickerColumnOption> = [];
  
  constructor(private pickerController: PickerController) {}

  onShowOptions(): void {
    const selectedIndex = this.findOptionIndex(this.defaultLanguage, this.languagesList);
    this.pickerController
      .create({
        columns: [
          {
            selectedIndex: selectedIndex,
            name: 'items',
            // here's where the magic happens: spread the object, remove duration & transform properties and keep the rest
            options: this.languagesList.map(({ duration, transform, ...rest }) => rest),
          },
        ],
        buttons: [
          {
            text: 'Cancel',
          },
          {
            text: 'Done',
            handler: ({ item }) => this.optionSelected(item),
          },
        ],
      })
      .then((picker: HTMLIonPickerElement) => picker.present());
  }

  private findOptionIndex(option: PickerColumnOption, list: Array<PickerColumnOption>): number {
    return list.findIndex((item: PickerColumnOption) => item.value === option.value);
  }
}
```

**Comment by sean-perkins** [comment]
Hello everyone 👋 

Can someone please test with this dev build and let me know if you continue to run into any issues?
```
6.0.14-dev.11648142586.16521a19
```

You should not need any workarounds for deleting values off the object.
