### ISSUE TITLE
bug: scroll assist cancels first click event

### ISSUE THREAD

**Issue by iphilgood** [ionic-team/ionic-framework#21871]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
An `ion-item` in a `ion-list` needs two clicks/taps to trigger the click event. This only happens on iOS (Safari/WebKit).

**Expected behavior:**
The event should trigger on the first click.

**Steps to reproduce:**

1. Create an `ion-list`
1. Within the `ion-list` create an `ion-item` with a `(click)` event handler
1. Within the `ion-item` create an `ion-label`
1. Within the `ion-item` create an `ion-input`
1. Within the `ion-item` create an `ion-button`

**Related code:**

This is the markup with which you can reproduce the issue. You can also find a GIF at the bottom of this issue.

```html
<ion-list>
  <ion-item (click)="onTitleClicked()" button detail="false">
    <ion-label position="floating">
      Title
    </ion-label>
    <ion-input [value]="title" readonly></ion-input>
    <ion-button
      *ngIf="title"
      slot="end"
      fill="clear"
      size="small"
      (click)="resetTitle($event)"
    >
      <ion-icon name="close"></ion-icon>
    </ion-button>
  </ion-item>
</ion-list>
```

I tried to narrow it down to the following, but the issue still persists.

```html
<ion-list>
  <ion-item (click)="onTitleClicked()" button detail="false">
    <ion-label>
      Title
    </ion-label>
    <ion-input [value]="title"></ion-input>
  </ion-item>
</ion-list>
```

You can find a sample application on [my GitHub](https://github.com/iphilgood/ionic-ion-item-click-bug).

**Other information:**
I found out that this change of behaviour was introduced with version `v5.0.6`. I've checked the [changes between the versions `v5.0.5` and `v5.0.6`](https://github.com/ionic-team/ionic-framework/compare/v5.0.5...v5.0.6) but I didn't find any suspicious code 🤔 

![ionic-bug](https://user-images.githubusercontent.com/126632/89261377-3c7ebd00-d62e-11ea-9fd0-7b3a16316a45.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (/Users/phil/.asdf/installs/nodejs/12.17.0/.npm/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v12.17.0 (/Users/phil/.asdf/installs/nodejs/12.17.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by iphilgood** [comment]
I've found out what the issue was. I will submit a PR shortly 🙌🏽

**Comment by ValisStigma** [comment]
Can confirm this

**Comment by iphilgood** [comment]
Well, I thought I found the issue but actually I didn't. 😅 For more information check out [the comment](https://github.com/ionic-team/ionic-framework/pull/21875#discussion_r465257039) from @liamdebeasi.

Hopefully, this gets fixed soon. If I can do anything, please let me know. I'm happy to help.

**Comment by lincolnthree** [comment]
I have been able to reproduce this sporadically as well using the (tap) event, however, in my case, switching to (click) seems to have been a passable workaround.

**Comment by longgt** [comment]
Maybe related to #20986

**Comment by lincolnthree** [comment]
Now that you mention it, this does only occur on iOS from the testing I've seen.

**Comment by fromage9747** [comment]
At least you can get it to click.  My ion-item button does not fire a click event at all...

**Comment by lincolnthree** [comment]
Actually it's been happening on Android as well. Do you have any custom Hammer.js recognizers configured?

**Comment by longgt** [comment]
```
Changing event listeners, like touchstart and touchmove to passive wherever possible.
```

may help a little bit. That's what I got from release notes in 4.10.4 of Mobiscroll.

**Comment by iphilgood** [comment]
Thanks to [this discussion on StackOverflow](https://stackoverflow.com/a/56830552) I found out that two clicks/taps are only necessary when using an `<ion-label>` with `position="floating"` or `position="stacked"`.

**Comment by florianmonfort** [comment]
> Thanks to [this discussion on StackOverflow](https://stackoverflow.com/a/56830552) I found out that two clicks/taps are only necessary when using an `<ion-label>` with `position="floating"` or `position="stacked"`.

@iphilgood hi, we have tried this solution and it doesn't work for us, so if anyone has suggestions for how to fix this is would be well appreciated.

**Comment by lydemann** [comment]
Can confirm as well in this demo with these steps:
Ion content with some padding (50px here) and scrollEvents true
--background-activated-opacity: 1 on item
Scroll to very bottom of list and click on an item
See list i "moving" and click is ignored, second click will work


`<ion-content [scrollEvents]="true" style="--padding-bottom: 50px;">
  <ion-item
    button
    style="--background-activated-opacity: 1"
    *ngFor="let item of items"
    (click)="onClick(item)"
  >
    <ion-label>{{ item }}</ion-label>
  </ion-item>
</ion-content>
`
https://github.com/lydemann/ionic-item-scrollend-click-bug

**Comment by liamdebeasi** [comment]
I can reproduce this. The issue is with the scroll assist utility. When scroll assist starts after an input is tapped, Ionic Framework calls `preventDefault` and `stopPropagation` on the `touchend` event, which cancels the click event: https://github.com/ionic-team/ionic-framework/blob/master/core/src/utils/input-shims/hacks/scroll-assist.ts#L29-L30

I can remove those lines, but I need to make sure it does not interfere with anything else.

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@5.6.0-dev.202101252121.ab1fc8f
```

**React**
```
npm install @ionic/react@5.6.0-dev.202101252121.ab1fc8f @ionic/react-router@5.6.0-dev.202101252121.ab1fc8f
```

**Vue**
```
npm install @ionic/vue@5.6.0-dev.202101252121.ab1fc8f @ionic/vue-router@5.6.0-dev.202101252121.ab1fc8f
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@5.6.0-dev.202101252121.ab1fc8f
```

**Comment by liamdebeasi** [comment]
> Can confirm as well in this demo with these steps:
> Ion content with some padding (50px here) and scrollEvents true
> --background-activated-opacity: 1 on item
> Scroll to very bottom of list and click on an item
> See list i "moving" and click is ignored, second click will work
> 
> ```
> <ion-content [scrollEvents]="true" style="--padding-bottom: 50px;">
>   <ion-item
>     button
>     style="--background-activated-opacity: 1"
>     *ngFor="let item of items"
>     (click)="onClick(item)"
>   >
>     <ion-label>{{ item }}</ion-label>
>   </ion-item>
> </ion-content>
> ```
> 
> https://github.com/lydemann/ionic-item-scrollend-click-bug

The dev build I posted appears to fix the repo you posted in https://github.com/ionic-team/ionic-framework/issues/22740, but https://github.com/lydemann/ionic-item-scrollend-click-bug seems like a different issue.

**Comment by iphilgood** [comment]
Thanks for your dev build! Awesome that this issue gets further investigated 🎉 

The click event gets now fired on first click but a funny thing is happening. The lower (like lower in the y axis) the item with input gets rendered, the longer it takes to fire the click event 🤔 In other words, the click on the very first item of a page gets fired faster than the click on the very last item of a page. 

Do you have an idea why this is happening?

I've updated the demo repo from my very first post with the new version and additional examples. This behaviour is actually reproducable in my demo repo.

**Comment by kensodemann** [comment]
@liamdebeasi - I have been working with someone on an issue related to this one and your dev build appears to fix the issue for them without causing other problems.

**Comment by liamdebeasi** [comment]
@iphilgood Can you try this dev build? It should fix the issue you mentioned.

**Angular**
```
npm install @ionic/angular@5.6.0-dev.202102011506.1af57ec
```

**React**
```
npm install @ionic/react@5.6.0-dev.202102011506.1af57ec @ionic/react-router@5.6.0-dev.202102011506.1af57ec
```

**Vue**
```
npm install @ionic/vue@5.6.0-dev.202102011506.1af57ec @ionic/vue-router@5.6.0-dev.202102011506.1af57ec
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@5.6.0-dev.202102011506.1af57ec
```

**Comment by iphilgood** [comment]
@liamdebeasi Thank you so much 🎉  I just tried it out and it works like a charm 😍 I tested it in our production app and in my demo repo. Finally, the issue seems to be resolved. I run some tests on an iPhone 8, iPhone 12 Pro and also on an Android device and everything works as expected.

Should I run some additional testing or can I support you in some other way? Please let me know.

**Comment by liamdebeasi** [comment]
Glad the issue is resolved. I merged in https://github.com/ionic-team/ionic-framework/pull/22845, the fix for this issue. This fix will be available in the next release of Ionic Framework.

Thanks!

**Comment by khain2007** [comment]
I still have the same issue with a checkbox within a ion-item. The checkbox is not checked/unchecked on the first tap (only in iOS, in Android it works like a charm).

**Comment by lincolnthree** [comment]
Still having this issue sporadically on things like buttons, the ion-back-button, and other elements. It seems to happen more near the edge of the screen than other places, though I'm not sure why that would be. Possibly menu gesture interaction?
