### ISSUE TITLE
bug: ion-refresher does not hide (iOS)

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/ionic-framework#22462]
Identical to #21291. I'm only opening a new bug report because that thread is locked and I can't comment.

@liamdebeasi were you able to get a hold of the webkit team on this? Is the only workaround the timeout hack?

**Comment by liamdebeasi** [comment]
Thanks for the issue, Yes, the WebKit issue was resolved and shipped as part of iOS 14.2.

**Comment by barrcodes** [comment]
Gotcha. Xcode doesn't has v14.1 simulators, so we were still seeing the bug. I tested on device, and it is fixed. Thanks!
