### ISSUE TITLE
bug: a11y - ion-popover does not close when VoiceOver is active

### ISSUE THREAD

**Issue by NeckbreakerPascal** [ionic-team/ionic-framework#22942]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

If Voice-Over is active on an iPhone the Popover is not closing. Even with the backdropDismiss option.

**Expected behavior:**

No matter if voiceOver is active or not, the Popover should close when the user clicks on a other element or the backdrop

**Steps to reproduce:**

- Create a template
- add a Popover programmatically like you see in the code snippet
- Build and run the app on an iPhone with activated VoiceOver
- Try to close the popover

**Related code:**

```

ts-file: 
// Function in the ts-file
  async presentPopover(ev: any) {
    const popover = await this.POPCTRL.create({
      component: PopovermediaComponent,
      componentProps: {
        permalink: this.data.permalink,
        id: this.data.id,
        containername: this.data.name,
        topline: this.data.topline,
        type : 'test',
        teaser: this.data.teasertext,
        mediathekURL: this.data.link,
        backdropDismiss: true
      },
      event: ev,
      translucent: true
    });
    return await popover.present();
  }


template: 
<ion-button class="sr-icon-popover ion-no-padding ion-no-margin" (click)="presentPopover($event)"><i aria-label="Menü  öffnen" class="fa fa-ellipsis-h" style="color: #024594;"></i></ion-button>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 30 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run (update available: 1.3.0)   : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v14.15.4 (/usr/local/bin/node)
   npm        : 2.15.12
   OS         : macOS Big Sur
   Xcode      : Xcode 12.4 Build version 12D4e

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try this again on the latest version of Ionic Framework? I believe this was fixed after v5.3.1.

**Comment by NeckbreakerPascal** [comment]
> Thanks for the issue. Can you try this again on the latest version of Ionic Framework? I believe this was fixed after v5.3.1.

Hey there, thanks for the fast reply. I installed the latest @ionic/angular 5.5.4 but the problem is still there.

**Comment by liamdebeasi** [comment]
Thanks! Can you reproduce this in an Ionic starter app and send a link to the repo?

**Comment by NeckbreakerPascal** [comment]
Will try to reproduce, but not sure if I can send the link to the repo. Will do my best. Thanks so far.
