### ISSUE TITLE
bug: [react] Page routing broken after opening modal

### ISSUE THREAD

**Issue by mauriceackel** [ionic-team/ionic-framework#23005]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x** (5.5.5)

**Current behavior:**
When the user is on a subpage, opens and closes a modal, the back animation is broken. If the modal has another nested modal inside, the whole page transition is not working. Please see the attached video:

https://user-images.githubusercontent.com/20804369/109803167-0257b700-7c21-11eb-84c8-60bc81faa0c4.mov

**Expected behavior:**
Opening/closing modals should not impact the page animations/transitions/routing.

**Steps to reproduce:**
Reproduction steps are explained in the provided code

**Related code:**
Please see the code in this repository: https://github.com/mauriceackel/react-routing-issue-example/tree/modal-issues
**IMPORTANT: Use the 'modal-issues' branch!**

**Comment by mauriceackel** [comment]
I did some more testing and the issue seems to be related to the fact that my example uses an <IonPage> element as a wrapper inside the IonModal component. Without the IonPage element, page transitions seem to work fine (can be tried in my demo repo).

However, the docs clearly state:
> If you need a wrapper element inside of your modal component, we recommend using an <IonPage> so that the component dimensions are still computed properly.

So I consider this either a bug or an issue in documentation.

**Comment by mauriceackel** [comment]
@elylucas Perhaps this is something you have the expertise with

**Comment by liamdebeasi** [comment]
Yep that looks like incorrect documentation. Those docs are true for Ionic Vue, but I don't think it is needed for React. I will update the docs to remove that statement.

**Comment by liamdebeasi** [comment]
Hi everyone,

I have merged in docs changes to remove this IonPage suggestion via https://github.com/ionic-team/ionic-framework/pull/23009. When the next release of Ionic Framework ships, you should see these changes go live in the docs.

**Comment by mauriceackel** [comment]
@liamdebeasi You missed a section of the documentation: https://ionicframework.com/docs/react/navigation#ionpage
(i.e. below the code sample)

**Comment by liamdebeasi** [comment]
Thanks! I will update that.
