### ISSUE TITLE
bug: Detail Icon in RTL direction

### ISSUE THREAD

**Issue by hussainarthuna** [ionic-team/ionic-framework#23078]
# Bug Report
Detail icon for ion-item not working properly when using RTL after upgrading to the V5.6.1, whereas it was working perfectly and as expected with V5.6.0

**Ionic version:**
[x] **5.x**

**Current behavior:**

Currently the Icon points to the right even if the Application Direction is RTl.

**Expected behavior:**

The Icon should rotate and point towards left in RTL and should point towards right in LTR.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.6.1
   @angular-devkit/build-angular : 0.1102.5
   @angular-devkit/schematics    : 11.2.5
   @angular/cli                  : 11.2.5
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run (update available: 1.3.0)   : 0.2.9

System:

   NodeJS : v14.15.0 (/usr/local/bin/node)
   npm    : 7.6.3
   OS     : macOS
   Xcode  : Xcode 12.4 Build version 12D4e

```

**Comment by hussainarthuna** [comment]
> # Bug Report
> Detail icon for ion-item not working properly when using RTL after upgrading to the V5.6.1, whereas it was working perfectly and as expected with V5.6.0
> 
> **Ionic version:**
> [x] **5.x**
> 
> **Current behavior:**
> 
> Currently the Icon points to the right even if the Application Direction is RTl.
> 
> **Expected behavior:**
> 
> The Icon should rotate and point towards left in RTL and should point towards right in LTR.
> 
> **Steps to reproduce:**
> 
> **Related code:**
> 
> ```
> insert short code snippets here
> ```
> 
> **Other information:**
> 
> **Ionic info:**
> 
> ```
> insert the output from ionic info here
> Ionic:
> 
>    Ionic CLI                     : 5.4.16
>    Ionic Framework               : @ionic/angular 5.6.1
>    @angular-devkit/build-angular : 0.1102.5
>    @angular-devkit/schematics    : 11.2.5
>    @angular/cli                  : 11.2.5
>    @ionic/angular-toolkit        : 3.1.1
> 
> Capacitor:
> 
>    Capacitor CLI   : 2.4.7
>    @capacitor/core : 2.4.7
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : android 8.1.0
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)
> 
> Utility:
> 
>    cordova-res (update available: 0.15.3) : 0.15.2
>    native-run (update available: 1.3.0)   : 0.2.9
> 
> System:
> 
>    NodeJS : v14.15.0 (/usr/local/bin/node)
>    npm    : 7.6.3
>    OS     : macOS
>    Xcode  : Xcode 12.4 Build version 12D4e
> ```

![IMG_1891](https://user-images.githubusercontent.com/46491137/111898786-1bda6a80-8a39-11eb-8979-aa2f91b5b95f.PNG)

**Comment by MuhAssar** [comment]
can confirm:
details arrows pointing to the wrong direction in RTL mode,
also the back arrow in the topbar has the same issue

ionic angular 5.6.1

![image](https://user-images.githubusercontent.com/2022065/111921937-f6cd1280-8a9f-11eb-99c3-fe2637a3c276.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem was triggered by this commit: https://github.com/ionic-team/ionic-framework/commit/c877061a328c6ab6fa7248b9880d0205c6c4f6c1

When we set `aria-hidden="true"` on `ion-icon`, an `aria-label` is never automatically generated. However, `ion-icon` requires that a label is set in order for the `flipRtl` property to work automatically: https://github.com/ionic-team/ionicons/blob/master/src/components/icon/icon.tsx#L158-L162

As a result, automatic RTL switching broke because of this change. I will work on a fix.

**Comment by hussainarthuna** [comment]
> Thanks for the issue. The problem was triggered by this commit: [c877061](https://github.com/ionic-team/ionic-framework/commit/c877061a328c6ab6fa7248b9880d0205c6c4f6c1)
> 
> When we set `aria-hidden="true"` on `ion-icon`, an `aria-label` is never automatically generated. However, `ion-icon` requires that a label is set in order for the `flipRtl` property to work automatically: https://github.com/ionic-team/ionicons/blob/master/src/components/icon/icon.tsx#L158-L162
> 
> As a result, automatic RTL switching broke because of this change. I will work on a fix.
> 
> Also need to investigate why our tests did not catch this, since it should have shown up in the screenshot diffs.

Thank you for the quick response, waiting for the fix in next update.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23081, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by liamdebeasi** [comment]
Hi everyone,

This fix has been released as part of Ionic Framework v5.6.2. Thanks for filing the issue!

**Comment by ZeeAziz** [comment]
@liamdebeasi The issue is still present in @ionic/angular 5.6.4
