### ISSUE TITLE
bug: ion-item with reactive forms

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23850]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

when using `ion-item` and `ion-input` with `ReactiveForms` along with `fill="outline` property, all `ion-item` in that page will be automatically red even though the input was not focus or touched yet. Below is the screenshot

<img width="599" alt="Screenshot 2021-08-30 at 11 10 46 PM" src="https://user-images.githubusercontent.com/61012396/131465029-716ee57b-ebd0-47e1-8f58-96f9fa20a4dd.png">

### Expected Behavior

When an `ion-item` has not been focused, it should instead not show any color and when its currently focused, it should show the primary color outline and when it is empty it should then be red.

When input is not focused
<img width="599" alt="Screenshot 2021-08-31 at 4 04 52 PM" src="https://user-images.githubusercontent.com/61012396/131466301-ab2d563f-7388-4d65-94bc-38fed8113284.png">

When an input is focused
<img width="599" alt="Screenshot 2021-08-31 at 4 05 00 PM" src="https://user-images.githubusercontent.com/61012396/131466650-8bd325c6-f5d4-4799-aa39-2181ce5b5b7a.png">

### Steps to Reproduce

in html file

```html
<form [formGroup]="myForm" (ngSubmit)="submit()">
    <ion-item fill="outline" class="ion-margin-bottom ion-margin-top">
      <ion-label position="stacked">Name</ion-label>
      <ion-input placeholder="Name" maxlength="40" formControlName="name"></ion-input>
    </ion-item>

    <ion-item fill="outline" class="ion-margin-bottom ion-margin-top">
      <ion-label position="stacked">Desc</ion-label>
      <ion-input placeholder="Desc" maxlength="40" formControlName="description"></ion-input>
    </ion-item>
</form>
```

in ts file

```typescript
myForm: FormGroup;

  constructor(
    private fb: FormBuilder
  ) { }

  ngOnInit() {
    this.myForm = this.fb.group({
      name: ['', [Validators.required]],
      description: ['', [Validators.required]],
    });
  }
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce the issue in an Ionic starter app and provide a link to the repo?

**Comment by farisfaisalthena** [comment]
https://github.com/farisfaisalthena/starter-repo

**Comment by farisfaisalthena** [comment]
Also, I have some other issues with `ion-item` can i just make a list here with the checklist or i have to open different issues on github?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23853, and a fix will be available in an upcoming release of the Ionic Framework v6 beta.

For other issues with `ion-item`, please create a separate issue. Separate issues make it easier for us to track individual changes and compile them in each Ionic release's changelog.

**Comment by farisfaisalthena** [comment]
Hi, I have updated the starter repo [here](https://github.com/farisfaisalthena/starter-repo). However this issue is not fully resolved as online the outline is fixed but the label will still be red
