### ISSUE TITLE
bug: IonLoading component does not render spinner in android

### ISSUE THREAD

**Issue by justinpathrose** [ionic-team/ionic-framework#24463]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

IonLoading component does not show spinner in android.

### Expected Behavior

IonLoading component should show spinner.

### Steps to Reproduce

Add an IonLoading component and build the app for android.
Open the app in android.

### Code Reproduction URL

https://github.com/justinpathrose/ion-loading-android

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/Users/justinv/.nvm/versions/node/v16.0.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.0.0 (/Users/justinv/.nvm/versions/node/v16.0.0/bin/node)
   npm    : 7.10.0
   OS     : macOS Big Sur

### Additional Information

Spinner renders in web, but does not render in android.

**Comment by sean-perkins** [comment]
Hello @justinpathrose thanks for the issue!

The issue here is that the `ion-spinner` custom element isn't being defined.

This issue has been fixed with this PR: #24439 and will be available in a new release after the Holidays. Let me know if there's a pressing timeline for you and I can make a dev build available. 

I'll update the PR description to additionally link this issue.

**Comment by hellokingdom** [comment]
@sean-perkins I have this issue also. Do you have an ETA on the new release or could you provide a dev build if possible. Many thanks.

**Comment by phpfs** [comment]
Any news to this? We still experience this issue with a project we started about 3 weeks ago…

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was fixed via https://github.com/ionic-team/ionic-framework/pull/24439, but we missed this issue when merging the fix in.

Please update to the latest version of Ionic 6 to receive a fix for this. If you are still running into problems, please open a new issue. Thanks!
