### ISSUE TITLE
bug: datetime confirm method ignores selected month and year when selection dropdown is still open

### ISSUE THREAD

**Issue by NilsFrkal** [ionic-team/ionic-framework#24962]
**Ionic version:**
[] **4.x**
[ ] **5.x**
[ x] **6.x**

[ x] bug report
[ ] feature request

**Current behavior:**

When using the date-time component (presentation="date") the selected year and month gets ignored when passed as element value. Example:

current date: 18/03/2022
selection:
   day: 15
   month: December
   year: 1980

console.log(dateinput.value): 15/03/2022

This behavior can be observed with all versions > @ionic/angular@6.0.1 i.e. 6.0.1 still works, all later versions up to 6.0.12 do not.  

**Expected behavior:**

Selected year and month should be considered i.e. expected output for example above 15/12/1980

**Steps to reproduce:**

1. Update to version > 6.0.1 e.g. latest version @ionic/angular@latest
2. Create date-time component   
3. Select a new date with month and year and pass in ionChange event via element value (see code snippet below)
4. Console.log value

To check working version:

1. npm install @ionic/angular@6.0.1
2. Create date-time component   
3. Select a new date with month and year and pass in ionChange event via element value (see code snippet below)
4. Console.log value

**Related code:**

 <ion-datetime id="XXX" [value]="date" presentation="date"
        (ionChange)="onSelectDate(dateinput.value)" showDefaultButtons="true"
        (ionCancel)="onDatePickerCancel()" #dateinput>
      </ion-datetime>

  onSelectDate (value) {
    console.log(value);
  }

**Ionic info:** 

Ionic:

   Ionic CLI                     : 6.19.0 (D:\Development\Nodist\bin\node_modules\@ionic\cli)  
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.3.0
   @angular-devkit/schematics    : 13.3.0
   @angular/cli                  : 13.3.0
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (D:\Development\Nodist\v-x64\16.13.2\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this? I cannot reproduce this behavior on my end.

**Comment by NilsFrkal** [comment]
While putting the test repo together I noticed something which should be relevant. The problem occurs only when you click the "Done" button when the Year / Month view is open. In 6.0.1 this resulted in still passing the correct date, but > 6.0.1 doesn't.

Git Repo: https://github.com/NilsFrkal/date-time-test

Thank you.

**Comment by amandaesmith3** [comment]
I'm unable to reproduce the issue using the repo; it looks like the logged value is always what I selected. Could you provide more detailed steps to reproduce? A screencast may help.

**Comment by NilsFrkal** [comment]
https://user-images.githubusercontent.com/12291453/160205661-9425b6aa-3cca-499d-a389-39adc89867e3.mp4

Recording attached. Please make sure that the show-default-buttons option is set to true as the error only occurs when using the default "Done" button to confirm the selection.

**Comment by DavidStrausz** [comment]
Is there a workaround or a dev build we can use until this is properly fixed? Option 3 from @amandaesmith3 suggestions sounds like a viable solution for us!

**Comment by dodomui** [comment]
Agree, it is really confusing to our user. Looking forward to a solution soon.

**Comment by ikosta** [comment]
@amandaesmith3 I've fixed it right now with an own confirm button but it would be also nice to have access to the [toggleMonthAndYearView](https://github.com/ionic-team/ionic-framework/blob/83186598ed6cf08b0f0421076c4afb3ab53e1e57/core/src/components/datetime/datetime.tsx#L1177) method because right now the state is not set correctly and the icon is therefore wrong.

It will work for us right now but it is ugly.

```ts
  public async confirm(): Promise<void> {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const nativeElement = (this.ionDatetime as any).el;

    /**
     * Since Ionic does not give us acess to the month and year toggle we need to get the native element
     * and check if the month and year is shown. If so we just close the month and year.
     */
    if (nativeElement.classList.contains('show-month-and-year')) {
      nativeElement.classList.remove('show-month-and-year');

      return;
    }

    await this.ionDatetime?.confirm(true);
  }
```

**Comment by SidiBecker** [comment]
> @amandaesmith3 I've fixed it right now with an own confirm button but it would be also nice to have access to the [toggleMonthAndYearView](https://github.com/ionic-team/ionic-framework/blob/83186598ed6cf08b0f0421076c4afb3ab53e1e57/core/src/components/datetime/datetime.tsx#L1177) method because right now the state is not set correctly and the icon is therefore wrong.
> 
> It will work for us right now but it is ugly.
> 
> ```ts
>   public async confirm(): Promise<void> {
>     // eslint-disable-next-line @typescript-eslint/no-explicit-any
>     const nativeElement = (this.ionDatetime as any).el;
> 
>     /**
>      * Since Ionic does not give us acess to the month and year toggle we need to get the native element
>      * and check if the month and year is shown. If so we just close the month and year.
>      */
>     if (nativeElement.classList.contains('show-month-and-year')) {
>       nativeElement.classList.remove('show-month-and-year');
> 
>       return;
>     }
> 
>     await this.ionDatetime?.confirm(true);
>   }
> ```

Hello @ikosta , I was use your code, but still exists  a little bug with toggle month/year . I able to improve UX, simulating the click on element, working in a better way.

```ts
public async confirmar(): Promise<void> {
    const nativeElement = (this.ionDatetime as any).el;

    if (nativeElement.classList.contains('show-month-and-year')) {
      const el: any =  nativeElement.shadowRoot.querySelector('.calendar-month-year');
      el.querySelector('ion-item').shadowRoot.querySelector('button').click()
      return;
    }

    await this.ionDatetime?.confirm(true);
  }
```

**Comment by amandaejohnston** [comment]
Hi folks, I've merged in https://github.com/ionic-team/ionic-framework/pull/25205 which hides the datetime footer when the month/year picker is open, solving this issue indirectly. You can see more info in the PR description. The update will be available in a future release of Ionic 👍

**Comment by ikosta** [comment]
Oh dear... hope our UX team is happy with that

**Comment by NilsFrkal** [comment]
I was also hoping we could simply re-implement the behavior from @ionic/angular@6.0.1 as it does work correctly in this version.

**Comment by liamdebeasi** [comment]
Hi everyone,

We made this change for a couple reasons:

1. Better consistency across platforms. 

We have found that maintaining separate layouts/behaviors across iOS and Android results in a lot of unexpected behaviors (for example, a behavior found only on iOS that users are expecting to also be found on Android). We are also a small team. We feel that managing two different implementations of datetime, a very complex component, is not in the best interest of the project.

2. Less confusion about what the Ok/Cancel buttons do.

We received feedback in https://github.com/ionic-team/ionic-framework/issues/24998 that showing the Ok/Cancel buttons when the month/year picker is open was confusing. Developers were expecting that the Ok/Cancel buttons would confirm only the wheel picker selector and then return you to the main calendar interface.

We explored simply adding a divider line between the picker and buttons, but ultimately decided not to go that route for accessibility reasons.

-----

I will also note that there is no change when using the `date`, `month`, `year`, `month-year`, or `time` `presentation` property values values.

We understand this change may not be what every developer is expecting, but we think this change will result in a better user experience for most users. Thanks!
