### ISSUE TITLE
bug: bundle size larger than expected with ionic 6 + webpack

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/ionic-framework#25005]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

This is a follow-up to https://github.com/ionic-team/ionic-framework/issues/24280, which was closed as fixed.  Unfortunately, I am still having the same issue-- in Ionic 5, with a React app, the [first big chunk of my app was about 500 Kb](https://user-images.githubusercontent.com/1451472/143669504-d821e8ec-c906-44d7-9a66-d7d2129aa86d.PNG), but with Ionic 6, it's 1.4 MB.

<img width="1253" alt="ionic_react_6_bundle_still_too_big" src="https://user-images.githubusercontent.com/1451472/160243600-7113ef39-5f46-435b-8fee-6738f2b3b204.png">

I also tried using the tool's "show bundle content (inaccurate) option:

<img width="1841" alt="more_bundle_info" src="https://user-images.githubusercontent.com/1451472/160243857-ea269778-516c-411a-bf78-4728b9639012.png">

What surprised me about the above result is that it shows that `ion-slides`, `ion-accordion-group`, `ion-breadcrumb`, and other components that I do not use in my app are being pulled in, so this is likely the source of the bloat.

### Expected Behavior

I expected Ionic 5 and 6 to be roughly the same size.

### Steps to Reproduce

Update a moderately sized app from v5 to v6.  I am using CRA5 with Webpack 5.

Tested with [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer)

`react-scripts build --stats; webpack-bundle-analyzer build/bundle-stats.json`

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/home/anon/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.13

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.1 (/usr/bin/node)
   npm    : 8.5.0
   OS     : Linux 5.10

**Comment by sean-perkins** [comment]
@ptmkenny thanks for reporting this issue.

While the PR for #24280 did partially improve the treeshaking behavior, the root issue was resolved in this recent PR: https://github.com/ionic-team/ionic-framework/pull/24989.

You can validate for yourself with this dev build:
```
6.0.14-dev.11648082573.18baa25a
```

Here is an example comparison with the blank Ionic react starter:

v6.0.13 stats:
```
All (1.82 MB)
static/js/main.0c17bc8e.js (525.47 KB)
static/js/6851.7ae66e16.chunk.js (103.3 KB)
static/js/2782.fea28aed.chunk.js (101.47 KB)
static/js/6893.be2a7b22.chunk.js (87.09 KB)
static/js/9850.a2a9cecc.chunk.js (81.09 KB)
static/js/2992.4c827afe.chunk.js (51.03 KB)
service-worker.js (50.07 KB)
... 
```

dev build stats:
```
All (621.99 KB)
static/js/main.52d52a81.js (437.56 KB)
static/js/851.7da1c8de.chunk.js (103.3 KB)
service-worker.js (46.2 KB)
static/js/372.419778ed.chunk.js (10.14 KB)
static/js/186.420eab5a.chunk.js (5.54 KB)
static/js/630.2e61bf51.chunk.js (5.42 KB)
static/js/738.17b07b18.chunk.js (5.41 KB)
static/js/377.dbc2ef09.chunk.js (3.44 KB)
static/js/215.b57031fa.chunk.js (2.24 KB)
static/js/856.282319a5.chunk.js (1.09 KB)
static/js/22.4a31d7e9.chunk.js (854 B)
static/js/841.db908d30.chunk.js (827 B)
```

Can you validate on your end and let me know if the build is still bloated?

**Comment by ptmkenny** [comment]
@sean-perkins Thank you for the response.

I set `"@ionic/core": "6.0.14-dev.11648082573.18baa25a",` in `package.json`, ran `npm up`, and rebuilt my app; unfortunately, I still see basically the same size (1.37 MB).

I deleted the `build` directory to ensure I wasn't getting something cached, and I also double-checked `package-lock.json` to ensure `@ionic/core` got updated.  Did I mess a step somewhere?

**Comment by sean-perkins** [comment]
@ptmkenny you will need to update the `@ionic/react` package version and remove any specific `@ionic/core` version, as it will pull in the correct version for the dev build:
```
"@ionic/react": "6.0.14-dev.11648082573.18baa25a"
```

The offending code for the treeshaking issue was an import to the hydrated bundle in `@ionic/react`.

**Comment by ptmkenny** [comment]
Actually, digging into this further, perhaps including things like `accordion` in `core/components` is the expected behavior?

I did some more testing with my actual app (not the repro repo) and found the following:

* Upgrading from Ionic 5 to 6, the size of the largest bundle increases significantly (more than doubles).
* Updating from Ionic 6 current release to the bugfix release, the largest bundle size stays the same, but the overall size of the app goes down significantly.

Largest individual bundle size vs. total app size

* Ionic 5: 677 kB / 2.79 MB
* Ionic 6 current: 1.37 MB / 3.89 MB
* Ionic 6 bugfix: 1.28 MB / 2.68 MB

Could you please confirm this is the expected behavior?  The overall bundle in 6 being smaller than 5 is great, but I'm a little worried that the much bigger initial bundle will slow down app load times.

Screenshots below.

Ionic 5 (CKEditor hidden):

<img width="1910" alt="ionic-5-no-ckeditor" src="https://user-images.githubusercontent.com/1451472/160736354-5c916ae2-5f62-492c-9516-6799c195cfa1.png">

Ionic 6 current release (CKEditor hidden):

<img width="1906" alt="ionic-6-old-no-ckeditor" src="https://user-images.githubusercontent.com/1451472/160736603-9d988c40-17ce-4225-be56-aae7e6c6ae1c.png">

Ionic 6 bugfix release (CKEditor hidden):

<img width="1903" alt="ionic-6-no-ckeditor" src="https://user-images.githubusercontent.com/1451472/160736416-4bcdf09d-9ce8-49c1-beed-45a83556a1ff.png">

**Comment by liamdebeasi** [comment]
Hey @ptmkenny,

There was indeed a treeshaking issue that @sean-perkins did a great job fixing. This fix is available now in Ionic 6.0.14. I observed a bundle size reduction in https://github.com/ptmkenny/ionic-react-bloat after building with v6.0.14.

I took a look at your reproduction, and I think `webpack-bundle-analzyer` may be misrepresenting the results.

When looking at `webpack-bundle-analyzer` it reports that `ion-picker.js` was processed. However, the source code for `ion-picker.js` was not actually found in the `build` directory for your app. I noticed in the screenshots that you have "Show contents of concatenated modules" enabled. This feature can yield inaccurate results, and I do not recommend using it as the basis for treeshaking analysis.

To test the true treeshaken bundle size, I looked at the total file size of all the non-source map JS files in `build/static`:

| v6.0.13 | v6.0.14 |
| ------- | ------- |
| 1.8mb  | 507kb   |

Can you try your build again and see if you can find any un-used Ionic modules imported in the `build` directory? I typically look in the `main.*.js` file.

**Comment by ptmkenny** [comment]
@liamdebeasi Ok thanks.  I had some more time to look at this and I see that the actual bundles are correct, and the `webpack-bundle-analyzer` output is inaccurate.

I'll close this now as the issue is completely solved in the latest release.  Many thanks for such a thorough solution!
