### ISSUE TITLE
bug: Vue, ion-content within ion-modal does not size the scroll container height correctly when using ion-header

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-framework#27586]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If an `ion-modal` has an `ion-content` with more content than will fit vertically, the `scroll` part of the `ion-content` does not take into account anything above the `ion-content`, such as an `ion-header`. As a result, you cannot scroll all the way to the bottom of the content.

### Expected Behavior

It would be nice if `ion-content::part(scroll)`'s `--offset-bottom` would be calculated as:

```
<ion-modal::part(content)>.offsetTop - <ion-content>.offsetTop
```

### Steps to Reproduce

1. Open the reproduction.
2. Click "Open Modal".
3. Try scrolling to the bottom. Notice the last item is not scrolled completely into view.
4. Uncomment line 23 (`--offset-bottom`). Now the last item can be scrolled completely into view.

### Code Reproduction URL

https://stackblitz.com/edit/fu8rda?file=src%2Fcomponents%2FExample.vue

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.0.0
   npm    : 9.6.4
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment]
Thanks for the report. I'm able to replicate this. Interestingly, it seems to only be happening in Vue; other frameworks (including core) correctly calculate the modal's scroll height.

This does not appear to be related to setting the `height` of the modal -- [this modification](https://stackblitz.com/edit/o7f6pt?file=src%2Fcomponents%2FExample.vue) of the [inline modal playground](https://ionicframework.com/docs/api/modal#inline-modals-recommended), which just adds the extra items to the content, also exhibits the bug.

Side note: the reproduction starts with line 23 already uncommented, so you have to comment it out to see the bug. I also noticed that the repro is a modified version of our [modal styling playground](https://ionicframework.com/docs/api/modal#styling) -- the main difference is that the toolbar has been moved out of the `ion-content` and into a separate `ion-header`.

**Comment by liamdebeasi** [comment]
Hi everyone,

We already fixed this in Ionic 7.0.9 (https://github.com/ionic-team/ionic-framework/commit/02678f3652be5139cf0c17d0f1260c145acd1a48). The StackBlitz provided was using Ionic 7.0.4 which is why the bug was showing up. I verified that the StackBlitz works as intended with v7.0.9. I am going to close this, but let me know if you have questions.

**Comment by amandaejohnston** [comment]
Looks like the root problem here is that our Vue playgrounds are currently configured to use Ionic 7.0.4, while others use the latest. We can investigate this internally. Thank you for raising this issue!

**Comment by aparajita** [comment]
@amandaejohnston @liamdebeasi I am still seeing the same behavior with my actual app with Ionic 7.0.10. Don't have time to reproduce it right now.

**Comment by amandaejohnston** [comment]
Once you can, please post a link to a Stackblitz app or minimal Github repo reproducing the issue on the latest Ionic, and we can take another look.
