### ISSUE TITLE
bug: webkit iOS 17, animation flicker

### ISSUE THREAD

**Issue by moerphie** [ionic-team/ionic-framework#28467]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Dismissing the modal triggers a flicker, perhaps the backdrop?
It only occurs irregularly. Never in Chrome, Safari rarely, iOS Simulator more often.

https://github.com/ionic-team/ionic-framework/assets/12500071/9ba93b9f-0598-4b3b-b465-ff894ecd98e5

### Expected Behavior

No flicker expected

### Steps to Reproduce

1. Clone this repo: https://github.com/moerphie/ionic-modal-flicker
2. ```yarn run install && yarn run dev```
3. Launch iOS Simulator and open/dismiss modal

### Code Reproduction URL

https://github.com/moerphie/ionic-modal-flicker

### Ionic Info

Ionic:

Ionic CLI : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/vue 7.5.3

Capacitor:

Capacitor CLI : 5.5.1
@capacitor/android : not installed
@capacitor/core : 5.5.1
@capacitor/ios : not installed

Utility:

cordova-res : not installed globally
native-run (update available: 2.0.0) : 1.7.4

System:

NodeJS : v16.17.0 (/usr/local/bin/node)
npm : 9.6.7
OS : macOS Unknown

**Comment by kim-hanho** [comment]
For someone looking for workaround: 
Hide backdrop element for a very short time between (willDismiss) and (didDismiss) events.
```html
<ion-modal
    #myModal
    (willDismiss)="myModal.showBackdrop = false"
    (didDismiss)="myModal.showBackdrop = true"
></ion-modal>
```
or
```html
<ion-modal
    [ngClass]={'hide-backdrop' : isHideBackdrop}
    (willDismiss)="isHideBackdrop = true"
    (didDismiss)="isHideBackdrop = false"
></ion-modal>
```
```CSS
ion-modal.hide-backdrop{
    &::part(backdrop){
        display:none
    }
}
```
I hope webkit will resolve the issue soon.

**Comment by liamdebeasi** [comment]
Hi everyone,

This has been resolved in the latest version of iOS.

**Comment by EinfachHans** [comment]
It's merged, but not released yet i think? Looks like it is not fixed in `17.4.1`

**Comment by liamdebeasi** [comment]
I believe it was fixed in iOS 17.5.

**Comment by philmmoore** [comment]
I'm on 17.5 beta but I'm still seeing the flicker :( 

![image](https://github.com/ionic-team/ionic-framework/assets/2862059/7474d023-0c6e-4c66-945c-b4b09c598ebf)

**Comment by dbousamra** [comment]
Also seeing issue

**Comment by philmmoore** [comment]
Hey @liamdebeasi I'm still seeing this in the latest beta release for 17.5 should we expect this to be resolved now?

**Comment by maximilien0405** [comment]
I'm still having this issue on modals on IOS 17.5 public beta !

**Comment by EinfachHans** [comment]
@maximilien0405 `ios 17.5` already has been released. Please check the final release, i don't have the problem anymore

**Comment by maximilien0405** [comment]
@EinfachHans I'm still having it.. sometime it flickers like in the video @philmmoore sent, sometime the backdrop dosen't have any fade-out animation and just disappears :/

**Comment by EinfachHans** [comment]
@maximilien0405 then i would recommend open a new issue with a small repo where the team can reproduce the issue and decide if it is an ionic or webkit bug

**Comment by felixhirschfeld** [comment]
I am also still seeing this. 
I am using this to fix it completely in React: 

`
<IonModal
isOpen={isOpen}
showBackdrop={isOpen}`/>

**Comment by Vasile-Peste** [comment]
The issue persists on latest version of iOS

**Comment by moerphie** [comment]
Still facing this issue in iOS as well as Chrome and Safari on macOS.
