### ISSUE TITLE
bug: ion-input not working properly with vite and @ionic/core

### ISSUE THREAD

**Issue by DeJy** [ionic-team/ionic-framework#30323]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Ion-input is not displayed correctly when I'm building my vanilla js project with vite.js. It works with version 7, but not with version 8. sc-ion-input-md is class is missing from the input tag.

### Expected Behavior

ion-input should display as ionic component and not standard html.

### Steps to Reproduce

1. see stackblitz.com project

### Code Reproduction URL

https://stackblitz.com/edit/sb1-tqcwwalu?file=package.json

### Ionic Info

Issue is with all v8 versions

**Comment by brandyscarney** [comment]
Thank you for the issue! It looks like this broke in `@ionic/core@8.2.7` with the update of Stencil to `@stencil/core@4.20.0`. I have added needs investigation to this ticket so that we can look into this further. I also created a dev build that downgrades Stencil if you would like to test that out: `npm i @ionic/core@8.5.3-dev.11743533952.19f90358`

**Comment by brandyscarney** [comment]
Additionally, I noticed adding this script to the `<head>` of the `index.html` works to include the styles if you want to try that approach until we find a solution:

```html
<script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
```

**Comment by DeJy** [comment]
this one is working as expected: @ionic/core@8.5.3-dev.11743533952.19f90358

**Comment by christian-bromann** [comment]
@DeJy what do you mean by _ion-input should display as ionic component and not standard html._?

Are you expecting Ionic to render the component as follows:

```patch
- <ion-input label="Fixed label" label-placement="fixed" placeholder="Enter text" class="sc-ion-input-md-h sc-ion-input-md-s md input-label-placement-fixed in-item hydrated">
+ <ion-input label="Fixed label" label-placement="fixed" placeholder="Enter text" class="sc-ion-input-md sc-ion-input-md-h sc-ion-input-md-s md input-label-placement-fixed in-item hydrated">
   <!---->
   <label class="input-wrapper" for="ion-input-0">
      <div class="label-text-wrapper">
         <div class="label-text">Fixed label</div>
      </div>
      <div class="native-wrapper sc-ion-input-md-s"><input class="native-input" id="ion-input-0" autocapitalize="off" autocomplete="off" autocorrect="off" name="ion-input-0" placeholder="Enter text" spellcheck="false" type="text"></div>
   </label>
</ion-input>
```

?

**Comment by DeJy** [comment]
I'm expecting this
 ```
 <ion-input label-placement="fixed" class="sc-ion-input-md-h sc-ion-input-md-s md input-label-placement-fixed hydrated">
    <label class="input-wrapper sc-ion-input-md" for="ion-input-0">
      <div class="label-text-wrapper sc-ion-input-md">
        <div class="label-text sc-ion-input-md">Fixed label</div>
      </div>
      <div class="native-wrapper sc-ion-input-md sc-ion-input-md-s">
        <input class="native-input sc-ion-input-md" id="ion-input-0" autocapitalize="off" autocomplete="off" autocorrect="off" name="ion-input-0" placeholder="Enter text" spellcheck="false" type="text" />
      </div>
      <div class="input-highlight sc-ion-input-md">
      </div>
    </label>
  </ion-input>
```
  But I'm getting this
 ```
 <ion-input label-placement="fixed" class="sc-ion-input-md-h sc-ion-input-md-s md input-label-placement-fixed hydrated">
    <label class="input-wrapper" for="ion-input-0">
      <div class="label-text-wrapper">
        <div class="label-text">
          Fixed label
        </div>
      </div>
      <div class="native-wrapper sc-ion-input-md-s">
        <input class="native-input" id="ion-input-0" autocapitalize="off" autocomplete="off" autocorrect="off" name="ion-input-0" placeholder="Enter text" spellcheck="false" type="text" />
      </div>
      <div class="input-highlight">
      </div>
    </label>
  </ion-input>
```

**Comment by DeJy** [comment]
The issue is not only with ion-input. As you can see in the example below, ion-alert that is opening from the ion-select doesn't have the right format.
https://stackblitz.com/edit/sb1-tqcwwalu?file=package.json

**Comment by christian-bromann** [comment]
Identified the responsible change in Stencil: https://github.com/stenciljs/core/pull/5892

**Comment by christian-bromann** [comment]
@DeJy can you help me understand what you are using the class names for?

**Comment by DeJy** [comment]
I'm not usign any specific ionic class names or ovewrite any of them in my custom css. 
I'm  just using this code `<ion-input label="Fixed label" label-placement="fixed" placeholder="Enter text"></ion-input>` which doesn't transpile and display correctly (see stackblitz exemple) when building my code with Vite and @ionic/core version 8.5.3. it works well with version 7.x..x of Ionic and with that build: @ionic/core@8.5.3-dev.11743533952.19f90358

I hope this answers your question.

**Comment by DeJy** [comment]
The example of the html above is the outcome of the build when I used version 8.5.3 (not working/not expected) vs 7.x.x (working/expected)

**Comment by christian-bromann** [comment]
Thanks for your feedback @DeJy - I've identified the issue and raised a PR with a fix in https://github.com/stenciljs/core/pull/6224

**Comment by christian-bromann** [comment]
A fix is on its way in #30132

**Comment by christian-bromann** [comment]
I published a dev build which resolves the issue: `8.5.4-dev.11743814940.14e938eb`. I will work with the Ionic team to get the PR merged and published.

**Comment by DeJy** [comment]
There is still an issue with LoadingController with the dev build (see here: https://stackblitz.com/edit/sb1-tqcwwalu?file=package.json), icon in the ion-spinner is not moving. The Loading pop-up style is now good, but he icon is not spinning as expected. Standalone ion-spinner is working well.

**Comment by DeJy** [comment]
is there an @ionic/core dev build that I can use until the fix is done on the next release?

**Comment by christian-bromann** [comment]
@DeJy we have logged the issue in https://github.com/stenciljs/core/issues/6219 and look at this individually from this ticket.

**Comment by christian-bromann** [comment]
A fix was released in Stencil and I was able to verify that this resolves the bug with the dev build `8.5.4-dev.11744646756.1244bf71`

**Comment by DeJy** [comment]
any target version to change stencil dependecy in Ionic to the good version?

**Comment by brandyscarney** [comment]
Thanks for the issue! This has been resolved by the update to Stencil in commit [808c60c](https://github.com/ionic-team/ionic-framework/commit/808c60c235af54f3eeb98af3723c180d1fc29dd5). It is available in the Ionic Framework [8.6.0](https://github.com/ionic-team/ionic-framework/releases/tag/v8.6.0) release. Please open a new issue if you are still running into problems after updating. 🙂
