### ISSUE TITLE
bug: Invinsible backdrop behind sheet modal on 8.7.4

### ISSUE THREAD

**Issue by SteliosMoch** [ionic-team/ionic-framework#30684]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

I have a map page with a sheet modal, the map includes clickable markers and buttons. After I updated to "@ionic/angular" to "8.7.4" I cannot press anything behind the sheet modal.
On chrome inspect there's a there's an overlay that doesn't me click anything behind my modal.
If I remove the modal I can then press the buttons.

<img width="372" height="732" alt="Image" src="https://github.com/user-attachments/assets/7aa4fa5b-1d8d-48f4-a0bd-110139f4e90c" />

### Expected Behavior

I expect to be able to press my buttons and markers behind the sheet modal.

### Steps to Reproduce

1. Install an Ionic Angular project
2. Add a sheet modal according to the documentation.
3. Add clickable items on the page.
4. Try to press the buttons that are behind the sheet modal.

### Code Reproduction URL

do not have one

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.1 (/Users/stelios/.nvm/versions/node/v22.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.7.4
   @angular-devkit/build-angular : 19.2.17
   @angular-devkit/schematics    : 19.2.17
   @angular/cli                  : 19.2.17
   @ionic/angular-toolkit        : 12.3.0

Capacitor:

   Capacitor CLI      : 7.4.3
   @capacitor/android : 7.4.3
   @capacitor/core    : 7.4.3
   @capacitor/ios     : 7.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v22.18.0 (/Users/stelios/.nvm/versions/node/v22.18.0/bin/node)
   npm    : 10.9.3
   OS     : macOS Unknown

**Comment by petrot** [comment]
Same here, I opened a modal form, and after save/close the modal, the parent list page is "disabled"..

**Comment by ggarg2** [comment]
I’m facing the same issue.

When I open a modal and then close it using ```@ViewChild``` reference, the screen gets stuck — I can’t scroll or tap anywhere.

```typescript
@ViewChild('customModal') customModal: IonModal;

if (this.customModal?.isCmpOpen) {
  await this.customModal?.dismiss();
}
``` 

However, if I close the modal with ```typescript modalController.dismiss()```, the stuck screen issue does not occur.

**Comment by poserr** [comment]
Same for ionic/react after upgrading from 8.7.3 to 8.7.4 

after opening and closing any ion-modal the main content section of ion-page becomes unusable (no click/scroll events), only tab bar is responsive, so I guess the issue has something to do with backdrop/overlays

**Comment by ShaneK** [comment]
I've tried reproducing this but I can't seem to. A good place to start with a reproduction would be the [Ionic Framework documentation on the modal page](https://ionicframework.com/docs/api/modal), going to a Stackblitz, then changing it to what needs to be changed to reproduce the errors. After you've reproduced it, save your fork and post it here.

Does it only happen when run natively? Does it only happen with Angular? Are you passing other parameters to your modal?

**Comment by SteliosMoch** [comment]
> I've tried reproducing this but I can't seem to. A good place to start with a reproduction would be the [Ionic Framework documentation on the modal page](https://ionicframework.com/docs/api/modal), going to a Stackblitz, then changing it to what needs to be changed to reproduce the errors. After you've reproduced it, save your fork and post it here.
> 
> Does it only happen when run natively? Does it only happen with Angular? Are you passing other parameters to your modal?

I created a repo for reproduction: https://github.com/SteliosMoch/modal-overlay-test

This problem happens both on my device, Samsung Galaxy S25 and on browser with 'ionic serve' command.

**Comment by poserr** [comment]
I finally reproduced my issue and it linked with conditional rendering of IonModal component where isOpen is fixed to true. I would agree that fixing isOpen={true} it is probably not the best approach, but tests did not show any problems with version <= 8.7.3. 

8.7.3 : https://stackblitz.com/edit/cst7dxnw-chwt1ajr?file=src%2FPage1.tsx
8.7.4 : https://stackblitz.com/edit/cst7dxnw-inpgicbw?file=src%2FPage1.tsx

**Comment by ShaneK** [comment]
Hey! Thank you so much for the reproductions. I was able to create regression tests for this and fix the issue, which was indeed caused by the recent aria-hidden changes.

If you'd like to test the PR before it's deployed, you can use this dev build:
```
8.7.5-dev.11758560050.1d0c4f0a
```

**Comment by NgLoader** [comment]
I still have the issue since version 8.7.4 when opening a modal that is assigned to a new parent and after it appears makes everything untouchable.
Also tested: ``8.7.5-dev.11758560050.1d0c4f0a``

https://stackblitz.com/edit/cst7dxnw-o5i8shu5

I changed the following lines:

Line: 23
```tsx
<IonContent className="ion-padding" id="example">
```

Line: 83
```tsx
<IonModal
  isOpen={true}
  onDidDismiss={() => {
    setIsOpen(false);
  }}
  onWillPresent={(event) => {
    document.getElementById('example')!.appendChild(event.target);
  }}
  breakpoints={[0.2, 0.5, 0.7]}
  initialBreakpoint={0.5}
>
```

With that, I’m able to display the modal above the toolbar.

My real code (snippet)
```ts
async open<C>(component: Type<C>, options: PopupOption, targetContainer?: Element): Promise<ComponentRef<C>> {
    await this.closeModal();

    const viewContainerRef = this._viewContainerService.viewContainer;
    const componentRef = viewContainerRef.createComponent(component);
    viewContainerRef.detach();

    // create new popup
    this.currentPopupComponent = componentRef;
    this.currentPopup = await this._modalController.create({
      ... options,
      component: DynamicComponentWrapperComponent,
      componentProps: {
        componetRef: this.currentPopupComponent
      }
    });

    // append current popup to only show up inside the view without toolbar
    if (targetContainer) {
      targetContainer.appendChild(this.currentPopup);
    }

    // add close listener and present popup
    this.currentPopup.present();
    this.currentPopup.onDidDismiss().then(() => this.closeModal());

    // return component ref
    return this.currentPopupComponent;
  }
```

**Comment by NgLoader** [comment]
Maybe I’m doing something wrong. I tested version 8.7.4 from @poserr and also installed the development build 8.7.5‑dev.11758560050.1d0c4f0a, but the issue still persists for me.

**Comment by ShaneK** [comment]
```typescript
  onDidPresent={(event) => {
    document.getElementById('example')!.appendChild(event.target);
  }}
```

Yeah, I'm not sure what you're trying to do with this, but you're shoving content in to the`ion-modal` instead of the content in the modal. This is not the right way to do this, the modal is the top layer and the content doesn't get appended directly to it like this.

If you grab the event.target and then find the ion-content in it and then add as a child to that, you may have better luck.

**Comment by NgLoader** [comment]
> If you grab the event.target and then find the ion-content in it and then add as a child to that, you may have better luck.

That was just for example, below that you can see my real implementation.


I'm just trying to create a modal that is presenting inside a declared area.
Here is a current working example with version 8.7.3:

![Image](https://github.com/user-attachments/assets/659a5656-0bc6-42a3-a3c9-72a3f150eca7)

**Comment by RowTracker** [comment]
I have a similar issue. The map click events stopped working on both IOS and android when any version of Ionic 8.7.1 or above is installed. All works correctly with 8.7.0 or below. Note I'm not using modal dialogs when showing a map.

The release notes for 8.7.1 just say it was a bump of the stencil/core version number but it was more than that when you look at the checkin diferences, notably HTMLElements have been replaced with HTMLStencilElements which suggests something bigger than just a version bump was done in this release.

**Comment by ShaneK** [comment]
Hey @RowTracker, that sounds like a different issue that you may want to report in a different issue thread with a reproduction.

**Comment by ShaneK** [comment]
Hey @NgLoader, I have a new dev build for you to try:
```
8.7.5-dev.11758642453.13b1da5d
```

Let me know if this helps!

**Comment by de-dan** [comment]
Hi @ShaneK I experience the same issue as described (also tested with your latest version 13b1da5d). I noticed one key difference between 8.7.3 and 8.7.4 (/8.7.5-dev.....): On my affected page the CSS class "backdrop-no-scroll" is added to the body. I hope that helps further debugging.

**Comment by ShaneK** [comment]
@de-dan I'm going to need a reproduction of this issue that doesn't work with `8.7.5-dev.11758642453.13b1da5d` because everything I have currently works and passes with it.

**Comment by NgLoader** [comment]
> Hey [@NgLoader](https://github.com/NgLoader), I have a new dev build for you to try:
> 
> ```
> 8.7.5-dev.11758642453.13b1da5d
> ```
> 
> Let me know if this helps!

Hey, thanks for trying to fix my issue, but it’s still occurring.

https://stackblitz.com/edit/cst7dxnw-o5i8shu5

Whenever you’re ready, I can send you a private Discord link for debugging (**ngloader**).
So you can see what is happening if the provided example is not good enough.

(I'm using Capacitorjs ``7.1.0`` with Angular ``20``)

**Comment by ShaneK** [comment]
Alright, so looks like this was specifically teleported modals.

Please try this new dev build:
```
 8.7.5-dev.11758652700.103435a3
```

**Comment by NgLoader** [comment]
Yep, its working now.

Will test it a little more but for the moment it seems fine.

**Comment by maximilianschmid** [comment]
@ShaneK 8.7.5-dev.11758652700.103435a3 fixes the issues introduced in 8.7.4 for us too

**Comment by ShaneK** [comment]
Hey everyone, thanks for your feedback on this issue! This has been released in today's patch, [v8.7.5](https://github.com/ionic-team/ionic-framework/releases/tag/v8.7.5)
